---
name: storybook

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, closed, synchronize, reopened]

jobs:
  test:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - run: |
          npm ci
          npm test

  deploy:
    if: github.event.pull_request.merged == false && github.event_name	== 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install & Build storybook
        run: |
          npm ci
          npm run build:storybook

      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Build and push
        uses: aevea/action-kaniko@master
        with:
          image: axentix/storybook-vue
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.BRANCH_NAME }}

      - name: Update image
        uses: distributhor/workflow-webhook@v2
        if: github.ref == 'refs/heads/master'
        env:
          webhook_url: '${{ secrets.WEBHOOK_URL }}'
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "container": "axentix-story-vue" }'

      - name: Update dev image
        uses: distributhor/workflow-webhook@v2
        if: github.ref == 'refs/heads/develop'
        env:
          webhook_url: '${{ secrets.WEBHOOK_URL }}'
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "container": "axentix-story-vue-dev" }'